export const appRoutes = {
    candidate: {
        dashboard: "/candidate/dashboard",
        browse: "/candidate/browse",
        history: "/candidate/history",
        availability: "/candidate/availability",
        settings: "/candidate/settings",
        professionalDetails: (professionalId: string) => `/candidate/professionals/${professionalId}`,
        professionalBook: (professionalId: string) => `/candidate/professionals/${professionalId}/book`,
        bookingDetails: (bookingId: string) => `/candidate/bookings/${bookingId}`,
        bookingReschedule: (bookingId: string) => `/candidate/bookings/${bookingId}/reschedule`,
        bookingDispute: (bookingId: string) => `/candidate/bookings/${bookingId}/dispute`,
        bookingReview: (bookingId: string) => `/candidate/bookings/${bookingId}/review`,
    },
    professional: {
        dashboard: "/professional/dashboard",
        requests: "/professional/requests",
        requestDetails: (bookingId: string) => `/professional/requests/${bookingId}`,
        requestConfirmAndSchedule: (bookingId: string) => `/professional/requests/${bookingId}/confirm-and-schedule`,
        requestReschedule: (bookingId: string) => `/professional/requests/${bookingId}/reschedule`,
        feedback: (bookingId: string) => `/professional/feedback/${bookingId}`,
        earnings: "/professional/earnings",
        settings: "/professional/settings",
    },
    admin: {
        bookings: "/admin/bookings",
        bookingDetails: (bookingId: string) => `/admin/bookings/${bookingId}`,
        disputes: "/admin/disputes",
        disputeDetails: (disputeId: string) => `/admin/disputes/${disputeId}`,
        users: "/admin/users",
        feedback: "/admin/feedback",
        payments: "/admin/payments",
    },
    api: {
        candidate: {
            busy: "/api/candidate/busy",
            professionalBookings: (professionalId: string) => `/api/candidate/professionals/${professionalId}/bookings`,
            bookingRescheduleRequest: (bookingId: string) => `/api/candidate/bookings/${bookingId}/reschedule/request`,
            bookingDispute: (bookingId: string) => `/api/candidate/bookings/${bookingId}/dispute`,
        },
        professional: {
            requestConfirmAndSchedule: (bookingId: string) => `/api/professional/requests/${bookingId}/confirm-and-schedule`,
            requestDecline: (bookingId: string) => `/api/professional/requests/${bookingId}/decline`,
            requestReschedule: (bookingId: string) => `/api/professional/requests/${bookingId}/reschedule`,
            requestRescheduleRequest: (bookingId: string) => `/api/professional/requests/${bookingId}/reschedule/request`,
            requestRescheduleConfirm: (bookingId: string) => `/api/professional/requests/${bookingId}/reschedule/confirm`,
            requestRescheduleReject: (bookingId: string) => `/api/professional/requests/${bookingId}/reschedule/reject`,
            feedback: (bookingId: string) => `/api/professional/feedback/${bookingId}`,
            onboarding: "/api/professional/onboarding",
        },
        admin: {
            bookingsExport: "/api/admin/bookings/export",
            bookingZoomLink: (bookingId: string) => `/api/admin/bookings/${bookingId}/zoom-link`,
            disputes: "/api/admin/disputes",
            disputeResolve: (disputeId: string) => `/api/admin/disputes/${disputeId}/resolve`,
            disputesExport: "/api/admin/disputes/export",
            usersExport: "/api/admin/users/export",
            feedbackExport: "/api/admin/feedback/export",
            paymentsExport: "/api/admin/payments/export",
        },
    },
} as const;
