export const appRoutes = {
    candidate: {
        browse: "/candidate/browse",
        chats: "/candidate/history",
        availability: "/candidate/availability",
        settings: "/candidate/settings",
        professionalDetails: (professionalId: string) => `/candidate/professionals/${professionalId}`,
        professionalBook: (professionalId: string) => `/candidate/professionals/${professionalId}/book`,
        bookingDetails: (bookingId: string) => `/candidate/bookings/${bookingId}`,
        bookingReschedule: (bookingId: string) => `/candidate/bookings/${bookingId}/reschedule`,
        bookingDispute: (bookingId: string) => `/candidate/bookings/${bookingId}/dispute`,
        bookingReview: (bookingId: string) => `/candidate/bookings/${bookingId}/review`,
    },
    professional: {
        dashboard: "/professional/dashboard",
        requests: "/professional/requests",
        requestDetails: (bookingId: string) => `/professional/requests/${bookingId}`,
        requestConfirmAndSchedule: (bookingId: string) => `/professional/requests/${bookingId}/confirm-and-schedule`,
        requestReschedule: (bookingId: string) => `/professional/requests/${bookingId}/reschedule`,
        feedback: (bookingId: string) => `/professional/feedback/${bookingId}`,
        earnings: "/professional/earnings",
        settings: "/professional/settings",
    },
    admin: {
        bookings: "/admin/bookings",
        bookingDetails: (bookingId: string) => `/admin/bookings/${bookingId}`,
        disputes: "/admin/disputes",
        disputeDetails: (disputeId: string) => `/admin/disputes/${disputeId}`,
        users: "/admin/users",
        feedback: "/admin/feedback",
        payments: "/admin/payments",
    },
    api: {
        auth: {
            signup: "/api/auth/signup",
            signupResume: "/api/auth/signup/resume",
            onboarding: "/api/auth/onboarding",
            role: "/api/auth/role",
            callbackRedirect: "/api/auth/callback-redirect",
            linkedProviders: "/api/auth/linked-providers",
            linkedProvider: (provider: string) => `/api/auth/linked-providers/${provider}`,
            forgotPassword: "/api/auth/forgot-password",
            resetPassword: "/api/auth/reset-password",
        },
        shared: {
            settings: "/api/shared/settings",
            reviews: "/api/shared/reviews",
            stripeAccount: "/api/shared/stripe/account",
            verificationRequest: "/api/shared/verification/request",
            verificationConfirm: "/api/shared/verification/confirm",
            verificationStatus: "/api/shared/verification/status",
            bookingCancel: (bookingId: string) => `/api/shared/bookings/${bookingId}/cancel`,
        },
        candidate: {
            availability: "/api/candidate/availability",
            busy: "/api/candidate/busy",
            reviews: "/api/candidate/reviews",
            uploadResume: "/api/candidate/upload/resume",
            profileById: (candidateId: string) => `/api/candidate/profile/${candidateId}`,
            professionalSearch: "/api/candidate/professionals/search",
            professionalDetails: (professionalId: string) => `/api/candidate/professionals/${professionalId}`,
            professionalReviews: (professionalId: string) => `/api/candidate/professionals/${professionalId}/reviews`,
            professionalBookings: (professionalId: string) => `/api/candidate/professionals/${professionalId}/bookings`,
            bookingRescheduleRequest: (bookingId: string) => `/api/candidate/bookings/${bookingId}/reschedule/request`,
            bookingDispute: (bookingId: string) => `/api/candidate/bookings/${bookingId}/dispute`,
        },
        professional: {
            requestConfirmAndSchedule: (bookingId: string) => `/api/professional/requests/${bookingId}/confirm-and-schedule`,
            requestDecline: (bookingId: string) => `/api/professional/requests/${bookingId}/decline`,
            requestReschedule: (bookingId: string) => `/api/professional/requests/${bookingId}/reschedule`,
            requestRescheduleRequest: (bookingId: string) => `/api/professional/requests/${bookingId}/reschedule/request`,
            requestRescheduleConfirm: (bookingId: string) => `/api/professional/requests/${bookingId}/reschedule/confirm`,
            requestRescheduleReject: (bookingId: string) => `/api/professional/requests/${bookingId}/reschedule/reject`,
            feedback: (bookingId: string) => `/api/professional/feedback/${bookingId}`,
            onboarding: "/api/professional/onboarding",
        },
        admin: {
            exportByTable: (table: "bookings" | "disputes" | "users" | "feedback" | "payments") => `/api/admin/export/${table}`,
            bookingZoomLink: (bookingId: string) => `/api/admin/bookings/${bookingId}/zoom-link`,
            disputes: "/api/admin/disputes",
            disputeResolve: (disputeId: string) => `/api/admin/disputes/${disputeId}/resolve`,
            paymentsRefund: "/api/admin/payments/refund",
            paymentsPayout: "/api/admin/payments/payout",
            bookingsExport: "/api/admin/export/bookings",
            disputesExport: "/api/admin/export/disputes",
            usersExport: "/api/admin/export/users",
            feedbackExport: "/api/admin/export/feedback",
            paymentsExport: "/api/admin/export/payments",
        },
        internal: {
            cron: {
                bookingsExpiry: "/api/internal/cron/bookings/expiry",
                bookingsNoShow: "/api/internal/cron/bookings/no-show",
                bookingsAttendanceRetention: "/api/internal/cron/bookings/attendance-retention",
            },
        },
    },
} as const;
